spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: '{cipher}AQAirAuTZJgYdvdPUJGkHwCHE0VJFRIn8B7BlpYLeF+w22KtCcYF6DsOyOHeTDir5l2nZwGjv6DifyUmIhQRNy2bnKMkL6GjEebbaNiuppEuSvSC/BQOCoYgiDcS7evy6XBnC5WBysamv9R/ROVcYpAQPl8hsHwpX9OU7FU82Mdfj+SZLPdkp0mGxZot0V34tfUiFcpJBLThh+1hnE5LEsbggNZ03ZCXMo2LWNYNECuZ8NTotQz4nSyDZCEMlfhaznY4SYWLpZSsF0EE1iExrVc0v47bCehzIdOg9hs3t2gDz1S9iPXTlW6HvGl3yZIljZVE0za5ywguLVeCRwXj3ORREcLjISk3xWuMxzZE8ciOCWYZ6V3ddpfPxMvBeenUhSU='
    generate-unique-name: true
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpstrace, busrefresh
