spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQAirAuTZJgYdvdPUJGkHwCHE0VJFRIn8B7BlpYLeF+w22KtCcYF6DsOyOHeTDir5l2nZwGjv6DifyUmIhQRNy2bnKMkL6GjEebbaNiuppEuSvSC/BQOCoYgiDcS7evy6XBnC5WBysamv9R/ROVcYpAQPl8hsHwpX9OU7FU82Mdfj+SZLPdkp0mGxZot0V34tfUiFcpJBLThh+1hnE5LEsbggNZ03ZCXMo2LWNYNECuZ8NTotQz4nSyDZCEMlfhaznY4SYWLpZSsF0EE1iExrVc0v47bCehzIdOg9hs3t2gDz1S9iPXTlW6HvGl3yZIljZVE0za5ywguLVeCRwXj3ORREcLjISk3xWuMxzZE8ciOCWYZ6V3ddpfPxMvBeenUhSU='


jwt:
  expiration: 86400000
  issuer: dev-haha
  secret: user-token-haha-hahaha

gateway:
  ip: 39.118.84.160

order-service:
  url: http://ORDER-SERVICE/order-service%s/orders
