spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa


jwt:
  expiration: 86400000
  issuer: haha
  secret: user-token-haha-hahaha

gateway:
  ip: 39.118.84.160

